spring.application.name=signalforge

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/signalforge
spring.datasource.username=signalforge
spring.datasource.password=signalforge

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info