package com.kritika.signalforge.audit;

public enum AuditAction {
    ACCESS_REQUEST_CREATED, ACCESS_REQUEST_APPROVED, ACCESS_REQUEST_REJECTED,
    USER_ROLE_CHANGED, INCIDENT_ACKNOWLEDGED, INCIDENT_RESOLVED
}
